// Synthetic mock: all people, relationships, records, identifiers, amounts, limits, dates, and entity associations are invented.
import { KidProfile, TriageTransaction, RuleSuggestion } from './types';

export const kids: KidProfile[] = [
  { id: 'jake', name: 'Jake', color: 'blue' },
  { id: 'emma', name: 'Emma', color: 'purple' },
  { id: 'sophie', name: 'Sophie', color: 'green' },
];

export const mockTransactions: TriageTransaction[] = [
  {
    id: 'txn-001',
    merchantName: 'AMZN MKTP US*2K4XF7',
    amount: -47.83,
    date: '2026-06-18',
    cardLabel: 'Chase Sapphire',
    cardLast4: '9876',
    originalCategory: undefined,
    triageStatus: 'uncategorized',
    suggestedCategories: ['Shopping', 'Kids - Entertainment', 'Household', 'Groceries'],
  },
  {
    id: 'txn-002',
    merchantName: 'CHICK-FIL-A #02341',
    amount: -14.32,
    date: '2026-06-17',
    cardLabel: 'Chase Sapphire',
    cardLast4: '9876',
    originalCategory: 'Fast Food',
    triageStatus: 'suggested-kid',
    suggestedKidId: 'jake',
    suggestedKidName: 'Jake',
    suggestionReason: 'Pattern match: assigned to Jake 8 of last 10 times',
    suggestionConfidence: 'likely',
  },
  {
    id: 'txn-003',
    merchantName: 'STEAM PURCHASE',
    amount: -59.99,
    date: '2026-06-16',
    cardLabel: 'Amex Blue Cash',
    cardLast4: '1234',
    originalCategory: 'Gaming',
    triageStatus: 'flagged',
    suggestedKidId: 'jake',
    suggestedKidName: 'Jake',
    flagReason: 'Jake already at $52 this week on gaming. Combined: $112 (over $100 weekly limit)',
  },
  {
    id: 'txn-004',
    merchantName: 'SEPHORA #1892',
    amount: -34.50,
    date: '2026-06-16',
    cardLabel: 'Amex',
    cardLast4: '7890',
    originalCategory: 'Beauty',
    triageStatus: 'suggested-kid',
    suggestedKidId: 'emma',
    suggestedKidName: 'Emma',
    suggestionReason: "Emma's card used directly",
    suggestionConfidence: 'definite',
  },
  {
    id: 'txn-005',
    merchantName: 'COSTCO WHSE #0392',
    amount: -287.42,
    date: '2026-06-15',
    cardLabel: 'Visa',
    cardLast4: '3456',
    originalCategory: 'General',
    triageStatus: 'uncategorized',
    suggestedCategories: ['Groceries', 'Household', 'Shopping'],
  },
  {
    id: 'txn-006',
    merchantName: 'NIKE.COM',
    amount: -89.99,
    date: '2026-06-15',
    cardLabel: 'Chase Sapphire',
    cardLast4: '9876',
    originalCategory: undefined,
    triageStatus: 'uncategorized',
    suggestedKidId: 'jake',
    suggestedKidName: 'Jake',
    suggestedCategories: ['Shopping', 'Clothing', 'Kids - Clothing'],
  },
  {
    id: 'txn-007',
    merchantName: 'SPOTIFY USA',
    amount: -15.99,
    date: '2026-06-15',
    cardLabel: 'Chase Freedom',
    cardLast4: '5678',
    originalCategory: 'Subscriptions',
    triageStatus: 'suggested-kid',
    suggestedKidId: 'emma',
    suggestedKidName: 'Emma',
    suggestionReason: "Emma's Spotify family plan sub-account",
    suggestionConfidence: 'likely',
  },
  {
    id: 'txn-008',
    merchantName: 'GAMESTOP #4521',
    amount: -44.99,
    date: '2026-06-14',
    cardLabel: 'Amex Blue Cash',
    cardLast4: '1234',
    originalCategory: 'Shopping',
    triageStatus: 'flagged',
    suggestedKidId: 'jake',
    suggestedKidName: 'Jake',
    flagReason: 'Jake purchased game at GameStop. Combined weekly gaming: $97 (approaching $100 limit)',
  },
  {
    id: 'txn-009',
    merchantName: 'TARGET #2290',
    amount: -62.31,
    date: '2026-06-14',
    cardLabel: 'Chase Sapphire',
    cardLast4: '9876',
    originalCategory: 'General Merchandise',
    triageStatus: 'uncategorized',
    suggestedCategories: ['Household', 'Kids - School', 'Shopping', 'Groceries'],
  },
  {
    id: 'txn-010',
    merchantName: 'MCDONALD\'S #38291',
    amount: -8.47,
    date: '2026-06-14',
    cardLabel: 'Chase Sapphire',
    cardLast4: '9876',
    originalCategory: 'Fast Food',
    triageStatus: 'suggested-kid',
    suggestedKidId: 'sophie',
    suggestedKidName: 'Sophie',
    suggestionReason: 'Sophie\'s soccer practice location — likely her lunch',
    suggestionConfidence: 'likely',
  },
  {
    id: 'txn-011',
    merchantName: 'ROBLOX *PURCHASE',
    amount: -19.99,
    date: '2026-06-13',
    cardLabel: 'Amex Blue Cash',
    cardLast4: '1234',
    originalCategory: 'Gaming',
    triageStatus: 'flagged',
    suggestedKidId: 'sophie',
    suggestedKidName: 'Sophie',
    flagReason: 'Sophie made 3 Roblox purchases this week totaling $45. Monthly limit: $30',
  },
  {
    id: 'txn-012',
    merchantName: 'UBER EATS',
    amount: -32.18,
    date: '2026-06-13',
    cardLabel: 'Chase Sapphire',
    cardLast4: '9876',
    originalCategory: 'Food Delivery',
    triageStatus: 'suggested-kid',
    suggestedKidId: 'jake',
    suggestedKidName: 'Jake',
    suggestionReason: 'Delivered to Jake\'s dorm address',
    suggestionConfidence: 'likely',
  },
  {
    id: 'txn-013',
    merchantName: 'WALGREENS #5839',
    amount: -15.43,
    date: '2026-06-13',
    cardLabel: 'Visa',
    cardLast4: '3456',
    originalCategory: undefined,
    triageStatus: 'uncategorized',
    suggestedCategories: ['Health', 'Personal Care', 'Household'],
  },
  {
    id: 'txn-014',
    merchantName: 'APPLE.COM/BILL',
    amount: -2.99,
    date: '2026-06-12',
    cardLabel: 'Amex',
    cardLast4: '7890',
    originalCategory: 'Subscriptions',
    triageStatus: 'suggested-kid',
    suggestedKidId: 'emma',
    suggestedKidName: 'Emma',
    suggestionReason: "Billed to Emma's iCloud storage plan",
    suggestionConfidence: 'definite',
  },
  {
    id: 'txn-015',
    merchantName: 'FIVE BELOW #892',
    amount: -22.50,
    date: '2026-06-12',
    cardLabel: 'Chase Freedom',
    cardLast4: '5678',
    originalCategory: 'Shopping',
    triageStatus: 'suggested-kid',
    suggestedKidId: 'sophie',
    suggestedKidName: 'Sophie',
    suggestionReason: 'Near Sophie\'s school — likely after-school purchase',
    suggestionConfidence: 'likely',
  },
];

export const ruleSuggestions: RuleSuggestion[] = [
  {
    merchantPattern: 'CHICK-FIL-A',
    kidName: 'Jake',
    assignmentCount: 5,
    suggestedConfidence: 'definite',
  },
  {
    merchantPattern: 'SEPHORA',
    kidName: 'Emma',
    assignmentCount: 4,
    suggestedConfidence: 'likely',
  },
];
